########################################################################
#                                                                      #
#              This file is part of the ksh 93u+m package              #
#          Copyright (c) 1984-2012 AT&T Intellectual Property          #
#          Copyright (c) 2020-2026 Contributors to ksh 93u+m           #
#                      and is licensed under the                       #
#                 Eclipse Public License, Version 2.0                  #
#                                                                      #
#                A copy of the License is available at                 #
#      https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html      #
#         (with md5 checksum 84283fa8859daf213bdda5a9f8d1be1d)         #
#                                                                      #
#                 Glenn Fowler <gsf@research.att.com>                  #
#                  Martijn Dekker <martijn@inlv.org>                   #
#                                                                      #
########################################################################

# Generator for *.req library dependency files with dependency probes.
# This script is based on the the code generated by the nmake MAPLIB
# rule from src/cmd/INIT/MAPLIB.mk, and replaces the latter.

# Set options.
case ${ZSH_VERSION+z} in
z)	emulate ksh ;;
*)	(command set -o posix) 2>/dev/null && set -o posix ;;
esac
set -o noglob -o nounset

case $(getopts '[-][123:xyz]' opt --xyz 2>/dev/null; echo 0$opt) in
0123)	optstring=$'
[-?
@(#)$Id: mkreq-maplib (ksh 93u+m) 2026-09-14 $
]
[-author?Glenn Fowler <gsf@research.att.com>]
[-author?Martijn Dekker <martijn@inlv.org>]
[-copyright?(c) 1984-2012 AT&T Intellectual Property]
[-copyright?(c) 2020-2026 Contributors to ksh 93u+m]
[-license?https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html]
[+NAME?mkreq-maplib - MAM *.req library dependency file generator with probes]
[+DESCRIPTION?The \bmkreq-maplib\b command may be called from \bMamfile\bs to
    generate a \b.req\b library dependency file for a given pre-existing
    library specified by \aself\a. It compiles the given C \asrc-file\as and
    tries to link them against each candidate library in turn, recording only
    the libraries actually required. The first line of \aself\a\b.req\b is
    '\'$'\b -l\b\aself\a'\'$' if \blib\b\aself\a exists on the system,
    '\'$'\b -\b'\'$' otherwise. For each \aname\a specified, if compiling or
    linking any of the \asrc-file\as fails without the \b-l\b\aname\a flag
    but succeeds with it, a line containing '\'$' \b-l\b\aname\a'\'$' is
    added to \aself\a\b.req\b.]
[+?At some point after \bmkreq-maplib\b finishes, the invoker is expected to
    install the generated \aself\a\b.req\b file as
    \b$INSTALLROOT/lib/lib/\b\aself\a to make it available for dependency
    resolution by other source subdirectories that link to the library.]
[+INVOCATION?This command takes no options (except those documented by the
    \b--??help\b option). Series of arguments are separated by an argument
    containing only a colon (\b:\b). Compiler and linker flags are specified
    in the \acc-args\a series; these should specify how to compile and link
    the \asrc-file\as. The \aself\a argument specifies the basename of the
    library for which to probe its dependencies. Both \aself\a and \aname\a
    should be specified minus any \blib\b prefix.]
[+CAVEAT?The \asrc-file\a minimal C probe programs, which are only compiled
    and linked and never executed, will probably need to be written to work
    around compiler optimisation. Modern compilers may omit library function
    calls for which the result is considered known at compile time. This
    applies to function calls the compiler knows about, even if they do not
    exist in the local system'\'$'s libraries. As a result, linking succeeds
    on systems where it should not, defeating dependency detection. A
    portable way to avoid this optimisation is involving a dummy call to a
    universally available library function with a non-constant result, such
    as \brand\b(3), in an argument to the library function being probed.]
[+HISTORY?This script was added to the build system in 2024. It is based on,
     and replaces, the code generated by the \bnmake\b(1) MAPLIB rule
     previously at src/cmd/INIT/MAPLIB.mk.]

[ cc-args ... : self : src-files ... : name ... ]

[+SEE ALSO?\bmkreq\b(1), \bmamake\b(1), \bsrc/cmd/INIT/Mamfile\b]\n'
	;;
*)	optstring='';
	;;
esac
while getopts "$optstring" opt
do	:
done
shift $((OPTIND - 1))

# Get colon-separated compiler invocation from arguments.
# Like this whole build system, we assume arguments do not contain
# spaces, or if they do, that they are meant to be field-split.
allcc=
while	test "$#" -gt 0 && test "$1" != ":"
do	allcc=$allcc${allcc:+ }$1
	shift
done
test "${1-}" = ":" || { echo "$0: bad arguments" >&2; exit 1; }
shift

# Get the .req basename.
req=$1
shift
test "${1-}" = ":" || { echo "$0: bad arguments" >&2; exit 1; }
shift

# Get the source file names.
src=
while	test "$#" -gt 0 && test "$1" != ":"
do	src=$src${src:+ }$1
	shift
done
test "${1-}" = ":" || { echo "$0: bad arguments" >&2; exit 1; }
shift

# Get the libraries to test.
libs=
while	test "$#" -gt 0
do	# for each lib name also add '-'
	libs="$libs${libs:+ }$1 -"
	shift
done

# Setup.
trap 'set +o noglob; rm -rf "$req".exe*' 0

######### Main ##########
#  Generate .req file.  #
#########################
r=' -'
for i in $src
do	if	$allcc -c $i >/dev/null 2>&1
	then	rm $(basename $i .c).o &
		g=
		for p in $libs
		do	case $p in
			-)	if	$allcc -o $req.exe $i $g >/dev/null 2>&1
				then	if	! $allcc -o $req.exe $i >/dev/null 2>&1
					then	r=$g
						break 2
					fi
				fi
				g=
				;;
			*)	g="$g -l$p"
				;;
			esac
		done
	fi
done
echo "$r" > $req.req
