########################################################################
#                                                                      #
#              This file is part of the ksh 93u+m package              #
#          Copyright (c) 1984-2012 AT&T Intellectual Property          #
#          Copyright (c) 2020-2026 Contributors to ksh 93u+m           #
#                      and is licensed under the                       #
#                 Eclipse Public License, Version 2.0                  #
#                                                                      #
#                A copy of the License is available at                 #
#      https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html      #
#         (with md5 checksum 84283fa8859daf213bdda5a9f8d1be1d)         #
#                                                                      #
#                 Glenn Fowler <gsf@research.att.com>                  #
#                  Martijn Dekker <martijn@inlv.org>                   #
#                                                                      #
########################################################################

# Generator for *.req library dependency files.
# This script is designed to be called from Mamfiles only.
# It is a heavily refactored version of the code generated
# by the nmake LIBS_req rule, and replaces the latter.

# Set options.
case ${ZSH_VERSION+z} in
z)	emulate ksh ;;
*)	(command set -o posix) 2>/dev/null && set -o posix ;;
esac
set -o noglob -o nounset
CCn='
' # one newline

case $(getopts '[-][123:xyz]' opt --xyz 2>/dev/null; echo 0$opt) in
0123)	optstring=$'
[-?
@(#)$Id: mkreq (ksh 93u+m) 2026-09-14 $
]
[-author?Glenn Fowler <gsf@research.att.com>]
[-author?Martijn Dekker <martijn@inlv.org>]
[-copyright?(c) 1984-2012 AT&T Intellectual Property]
[-copyright?(c) 2020-2026 Contributors to ksh 93u+m]
[-license?https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html]
[+NAME?mkreq - MAM *.req library dependency file generator]
[+DESCRIPTION?The \bmkreq\b command is invoked from \bMamfile\bs to generate
    a \aself\a\b.req\b library dependency file for a library being built,
    \blib\b\aself\a. The first line of \aself\a\b.req\b is always '\'$'
    \b-l\b\aself\a'\'$'. For each \alibname\a, it first looks for a
    dependency file in \b$INSTALLROOT/lib/lib/\b\alibname\a and if found,
    those dependencies are incorporated in \aself\a\b.req\b. If not,
    \bmkreq\b attempts to link a dummy C program against each \alibname\a
    specified, which determines whether it is possible to link against that
    candidate library on the local system. Unlike \bmkreq-maplib\b(1), this
    program makes no attempt to determine whether the library is actually
    required; it assumes that every specified \alibname\a for which linking
    succeeds is required. For each library where linking succeeds, it writes
    an \b-l\b flag to \aself\a\b.req\b on a single line preceded by a space.
    As a final step, it deduplicates the dependencies gathered while keeping
    them in the correct order for passing on to the linker, with each
    dependency coming after (!) all the libraries that depend on it.]
[+?At some point after \bmkreq\b finishes, the invoker is expected to install
    the generated \aself\a\b.req\b file as \b$INSTALLROOT/lib/lib/\b\aself\a
    to make it available for dependency resolution by other source
    subdirectories that link to the library.]
[+INVOCATION?This command takes no options (except those documented by the
    \b--??help\b option). Compiler arguments and linker flags are specified
    as arguments, each terminated by an argument consisting of a colon
    (\b:\b); these should specify how to compile and link the minimal test
    program. Each \alibname\a represents a possible dependency of the library
    and should be specified as a library basename minus any \blib\b prefix.]
[+HISTORY?This script was added to the build system in 2023. It is loosely
     based on, and replaces, the code generated by the \bnmake\b(1) LIBS_req
     rule. Deduplication was added in 2024.]

compiler-argument ... : linker-flag ... : self libname ...

[+SEE ALSO?\bmkreq-maplib\b(1), \bmkdeps\b(1), \bmamake\b(1)]\n'
	;;
*)	optstring='';
	;;
esac
while getopts "$optstring" opt
do	:
done
shift $((OPTIND - 1))

: $INSTALLROOT	# error out early

# Get colon-separated compiler and linker invocations from arguments.
# Like this whole build system, we assume arguments do not contain
# spaces, or if they do, that they are meant to be field-split.
allcc=
while	test "$#" -gt 0 && test "$1" != ":"
do	allcc=$allcc${allcc:+ }$1
	shift
done
test "${1-}" = ":" || { echo "$0: bad arguments" >&2; exit 1; }
shift
ldflags=
while	test "$#" -gt 0 && test "$1" != ":"
do	ldflags=$ldflags${ldflags:+ }$1
	shift
done
test "${1-}" = ":" || { echo "$0: bad arguments" >&2; exit 1; }
shift

# Setup.
trap 'set +o noglob; rm -rf mkreq.$$.*' 0
echo 'int main(void) { return 0; }' > mkreq.$$.c
$allcc -c mkreq.$$.c || exit

# Function: try to link the test program with possible extra linker flags.
try_to_link()
{
	_lib=$1
	shift
	# Delete any previous test binary (including any OS-specific extra files).
	test -e mkreq.$$.x && (set +o noglob; rm -rf mkreq.$$.x*)
	# Try to link.
	$allcc ${1+"$@"} $ldflags -o mkreq.$$.x mkreq.$$.o -l${_lib} 2>/dev/null || return
	# To work around possible linker breakage, we have to
	# actually run the test program, not merely link it.
	./mkreq.$$.x
	e=$?
	if	test "$e" -gt 0
	then	if	test "$e" -gt 128 &&
			test "$(kill -l $e)" = "ABRT" &&
			test "$(uname -s)" = "Darwin"
		then	echo "$0: THE ABOVE CRASH IS APPLE'S BUG, NOT OURS." >&2
			echo "$0: We have successfully worked around the bug." >&2
			echo "$0: https://github.com/ksh93/ksh/issues/596" >&2
		fi
		return 1
	fi
	return 0
}

######### Main ##########
#  Generate .req file.  #
#########################
self=$1
shift
exec >$self.req
echo " -l$self"
dupes=$(
for name
do	if	test -f $INSTALLROOT/lib/lib/$name
	then	grep '^ -l.' $INSTALLROOT/lib/lib/$name
		continue
	elif	test ! -f $INSTALLROOT/lib/lib$name.a
	then	try_to_link $name -L$INSTALLROOT/lib || try_to_link $name || continue
	fi
	echo " -l$name"
done
)
# Remove duplicates from the set of newline-separated items in 'dupes'.
# Keep the last-mentioned of each item that occurs multiple times (this is
# required for passing libraries to the linker in the correct order; that
# is, each dependency must come after all the libraries that depend on it).
while	test -n "$dupes"
do	# Grab first item from dupes
	item=${dupes%%"$CCn"*}
	# Remove that item from dupes
	dupes=${dupes#"$item"}
	dupes=${dupes#"$CCn"} # remove $CCn separately as last item won't end in it
	# Skip the item if another identical item is still in dupes
	case "$CCn$dupes$CCn" in
	*"$CCn$item$CCn"*)
		continue ;;
	esac
	echo "$item"
done
