.TH AST 3
.SH NAME
ast \- miscellaneous libast support
.SH SYNOPSIS
.nf
.ft CR
#include <ast.h>

char*          astconf(const char* \fIname\fP, const char* \fIpath\fP, const char* \fIvalue\fP);
long           astconf_long(\fIarg\fP);
unsigned long  astconf_ulong(\fIarg\fP);
Ast_confdisc_t astconfdisc(Ast_confdisc_t new_notify);
void           astconflist(Sfio_t* stream, const char* path, int flags);
int            astquery(int \fIfd\fP, const char* \fIformat\fP , ...);
void           astwinsize(int \fIfd\fP, int* \fIrows\fP, int* \fIcols\fP);
.ft
.fi
.SH DESCRIPTION
\f[CB]astconf\fP
is a string interface to the
.IR confstr (3),
.IR pathconf (2),
and
.IR sysconf (3)
calls.
If
.I value
is
\f[CB]NULL\fP
then the configuration parameter value for
.I name
is returned.
Some
.I name
configuration parameters may consult the
.I path
argument.
In this case if
.I path
is
\f[CB]NULL\fP
then
\f3"/"\fP
is used.
Otherwise if
.I path
is not
\f[CB]NULL\fP
then it must exist.
The string return value for
.I name
remains unchanged until the next
.B astconf
call on
.IR name .
If
.I value
is
\f[CB]NULL\fP
then a valid string is always returned;
\f3""\fP
is returned if
.I name
has no configuration value.
This simplifies the programming interface:
.nf
.ft CR
if (!strcmp(astconf("PATH_RESOLVE", NULL, NULL), "logical"))
	/* the logical way ... */
.ft
.fi
If
.I value
is not
\f[CB]NULL\fP
then the configuration parameter value for
.I name
is set to
.IR value .
\f[CB]NULL\fP
is returned if the value cannot be set.
The paradigm is:
.nf
.ft CR
universe = astconf("UNIVERSE", 0, "att");
\|.\|.\|.
astconf("UNIVERSE", 0, universe);
.ft
.fi
The settable configuration names are:
.TP
\f[CB]PATH_RESOLVE\fP
\f[CB]logical\fP
if symbolic links are followed during file tree traversal,
\f[CB]physical\fP
if symbolic links are not followed during file tree traversal,
and
\f[CB]metaphysical\fP
if symbolic links are followed at the top level during file tree traversal.
These correspond to the generic
\f[CB]\-L\fR,
\f[CB]\-P\fR,
and
\f[CB]\-H\fP
command options.
.TP
\f[CB]UNIVERSE\fP
\f[CB]ucb\fP
for
.I Berkeley
style and
\f[CB]att\fP
otherwise.
This configuration parameter controls the
.I universe
setting on machines that support it (e.g., Pyramid).
\f[CB]UNIVERSE\fP
also controls the behavior of some commands like
.IR cat (1)
and
.IR echo (1).
.PP
User defined
.I name
values may also be set and queried, but these should probably have
some form of vendor prefix to avoid being stomped by future standards.
.PP
\f[CB]astconf_long\fP
and
\f[CB]astconf_ulong\fP
are macros that call either
.I sysconf
or
\f[CB]astconf\fR,
preferring
.I sysconf
if it's available.
\f[CB]astconf_long\fP
returns a signed long value while
\f[CB]astconf_ulong\fP
returns an unsigned long value.
The argument passed to these macros may be one of the following:
.nf
.ft CR
CONF_ARG_MAX
CONF_CHILD_MAX
CONF_CLK_TCK
CONF_NGROUPS_MAX
CONF_OPEN_MAX
CONF_PAGESIZE
.ft
.fi
.PP
\f[CB]astconfdisc\fP
registers a discipline function
.nf
.ft CR
int (*notify)(const char* \f[I]name\fP, const char* \f[I]path\fP, const char* \f[I]value\fP);
.ft R
.fi
that is called just before the configuration parameter
.I name
is set to
.I value
relative to
.IR path .
If
.I notify
returns
\f[CB]NULL\fP
then the configuration parameter value is not changed.
.PP
\f[CB]astconflist\fP
lists the current configuration names and values of
.IR stream .
If
.I path
is
\f[CB]NULL\fP
then \f3"/"\fP is used where appropriate.
If
.I flags
is
\f[CB]NULL\fP
or
\f[CB]R_OK|W_OK\fP
then all configuration parameters are listed.
\f[CB]R_OK\fP
lists the readonly configuration parameters and
\f[CB]W_OK\fP
lists the settable configuration parameters.
\f[CB]X_OK\fP
lists the settable configuration parameters in a form that can be
snarfed for input to the
.IR getconf (1)
command.
.PP
\f[CB]astquery\fP
outputs an
.IR sfprintf (3)
prompt specified by
.I "format, .\|.\|."
to the controlling terminal and reads a response from the controlling terminal.
Affirmative response returns
\f[CB]0\fR,
\f[CB]EOF\fP
or quit response returns
\f[CB]\-1\fR,
otherwise
\f[CB]1\fP
is returned.
If
.I quit
is greater than
\f[CB]NULL\fP
then
.I exit(quit)
is called on a quit response.
The responses will eventually be locale specific.
.PP
\f[CB]astwinsize\fP
returns the number of rows in
.I *rows
and the number of columns in
.I *cols
for the terminal file descriptor
.IR fd .
If the number of rows or columns cannot be determined or if
.I fd
is not a terminal then
.I *rows
and
.I *cols
are set to
\f[CB]0\fR.
If
.IR ioctl (2)
methods fail then the environment variable
\f[CB]LINES\fP
is used to set
.I *rows
and the environment variable
\f[CB]COLUMNS\fP
is used to set
.IR *cols .
.SH "SEE ALSO"
.IR getconf (1),
.IR confstr (3),
.IR mmap (2),
.IR pathconf (2),
.IR read (2),
.IR sysconf (3),
.IR write (2)
