.TH COMPATIBILITY 3
.SH NAME
compatibility \- AST library compatibility routines
.SH SYNOPSIS
.nf
.ft CW
#include <ast.h>

char*	mktemp(char*);
int	sigunblock(int);
double	strtod(const char*, char**);
long	strtol(const char*, char**, int);
char*	tmpnam(char*);
.ft
.fi
.SH DESCRIPTION
These routines are described in the ANSI C, POSIX, BSD and System V manual
sections 2 and 3.
The interfaces are preserved and present in all libast implementations.
Where conflicts exist the POSIX syntax and semantics are implied.
The appropriate error value is returned and
.I errno
is set to
\f(CWEINVAL\fP
when emulation is either too expensive or not possible.
.SH CAVEATS
If you
\f(CW#undef foo\fP
and then call
\f(CWfoo\fP
you may end up with the local implementation of
\f(CWfoo\fR,
and then you get what you paid for.
