.TH ERROR 3
.SH NAME
error \- error and debug trace message formatter
.SH SYNOPSIS
.nf
.ft CW
#include <error.h>

Error_info_t error_info;

void         error(int \fIlevel\fP, ...);
void         errorv(const char* \fIlibrary\fP, int \fIlevel\fP, va_alist \fIargs\fP);
int          errormsg(const char* \fIdictionary\fP, int \fIlevel\fP, ...);

#include <debug.h>

debug(\fIstatement\fP)
message((int \fIlevel\fP, ...))
messagef((void* \fIhandle\fP, void* \fIdiscipline\fP, int \fIlevel\fP, ...))
.ft
.fi
.SH DESCRIPTION
\f(CWerror\fP
is the error and debug trace message formatter.
.I level
is the severity level.
Messages with
.I "level < error_info.trace"
are suppressed.
.I error_info.trace
is initially
\f(CW0\fR.
The remaining arguments are passed on to
\f(CWprintf\fR.
A
.I newline
is appended to the message text, so none should appear in the
\f(CWprintf\fP
format.
If
.I error_info.id
is not
\f(CW0\fP
then messages with
.I "level > 0"
are prefixed by
.IR error_info.id: .
.PP
Before the message text is output to standard error
it is passed to the function
\f(CWchar* ERROR_translate(const char* \fItext\fP, int \fIflag\fP)\fR.
By default
\f(CWERROR_translate\fP
returns the
\f(CWtext\fP
argument, but on some systems it may do language translation via lookup
on the original source text.
\fR(\fP error
calls
\f(CWERROR_translate\fP
with a 0
\f(CWflag\fP
argument).
.PP
.I level
may be one of:
.TP
.B <0
Negative values are for debug tracing.
Debug messages are prefixed with
.BI debug level.
If
.I "errno != error_info.last_errno"
then
.I error_info.last_errno
is set to
.I errno
and the error text for errno is appended to the message.
.TP
.B "ERROR_INFO [0]"
Information only; no prefixes are added to the message.
.TP
.B "ERROR_WARNING [1]"
\f(CWwarning:\fP
is added after
\f(CWerror_info.id\fP
and
.I error_info.warnings
is incremented.
.TP
.B "ERROR_ERROR [2]"
(soft error)
.I error_info.errors
is incremented.
.TP
.B ">= ERROR_FATAL [3]"
(hard error)
.I error_info.errors
is incremented and
\f(CWexit(\fIlevel\fP\-2)\fP
is called after the message is emitted.
.TP
.B "ERROR_PANIC [130]"
(unrecoverable internal error)
\f(CWpanic:\fP
is added after
.IR error_info.id .
.PP
The following may be inclusive-or'd into
.I level
for alternate behavior:
.TP
.B ERROR_SYSTEM
The error text for
.I errno
is appended to the message.
.TP
.B ERROR_OUTPUT
The next argument is the file descriptor where the error message
should be emitted.
.TP
.B ERROR_SFIO_OUT
The next argument is the Sfio stream where the error message
should be emitted.
.TP
.B ERROR_SOURCE
Then next two arguments are a file name and line number that are added
to the message after
.IR error_info.id .
.TP
.B ERROR_USAGE
A usage message is emitted.
.TP
.B ERROR_PROMPT
The trailing
.I newline
is suppressed.
.TP
.B ERROR_NOID
The
.I error_info.id
prefix is suppressed.
.TP
.B ERROR_LIBRARY
The message is from a library routine.
.SH ENVIRONMENT
The elements of the global struct
.I error_info
control error output and actions.
Parts of
.I error_info
can be initialized from the
\f(CWERROR_OPTIONS\fP
environment variable.
\f(CWERROR_OPTIONS\fP
contains space separated
.IR name [ =value ]
options, described below.
.TP
.I "int core"
If
.I "error_info.core != 0"
then
.I "level >= error_info.core"
generates a core dump.
Initialized by
.nf
.ft CW
ERROR_OPTIONS="core=\fIlevel\fP"
.ft
.fi
where
.I level
can be a number or one of
\f(CWerror\fR,
\f(CWfatal\fR,
or
\f(CWpanic\fR.
.I error_info.core
is a handy way to get a stack trace at the exact point of error.
.TP
.I "int error_info.trace"
If
.I "error_info.trace != 0"
and
.I "level < error_info.trace"
then the error message text is suppressed.
\f(CWexit()\fP
may still be called if appropriate for
.IR level .
Initialized by
.nf
.ft CW
ERROR_OPTIONS="trace=\fIlevel\fP"
.ft
.fi
where
.I error_info.trace
is set to the negative of
.IR level .
.PP
Library error messages, suppressed by default, are enabled by
.nf
.ft CW
ERROR_OPTIONS="library"
.ft
.fi
The system
.I errno
message text can be forced for each message by
.nf
.ft CW
ERROR_OPTIONS="system"
.ft
.fi
.SH "EXTENDED DESCRIPTION"
\f(CW<debug.h>\fP
provides debugging message macros when
\f(CWDEBUG\fP
or
\f(CW_BLD_DEBUG\fP
are defined
\fR(\fP _BLD_DEBUG
is defined by
the
.IR Mamfile s
when the
\f(CW\-G\fP
a.k.a.
\f(CW\-\-debug\-symbols\fP
option is passed to
.BR mamake (1),
which the
.BR package (1)
command does automatically when given the argument
\f(CWdebug=1\fR).
All of the macros expand to nothing when both
\f(CWDEBUG\fP
and
\f(CW_BLD_DEBUG\fP
are not defined.
Otherwise
\f(CWdebug\fP
expands its arg and
\f(CWmessagef\fP
and
\f(CWmessage\fP
call
\f(CWerrorf\fP
and
\f(CWerror\fP
respectively if
.IR "error_info.trace<0" .
Notice that
\f(CWmessagef\fP
and
\f(CWmessage\fP
are macro hacks that require double parentheses ((...)) around the
arguments.
.SH EXAMPLE
To enable debugging message level -3, library messages, and system
.I errno
text for all commands:
.nf
.ft CW
export ERROR_OPTIONS="trace=3 library system"
.ft
.fi
