.TH GETCWD 3
.SH NAME
getcwd \- return absolute path to current directory
.SH SYNOPSIS
.nf
.ft CR
#include <ast.h>

char* getcwd(char* \fIbuf\fP, size_t \fIlen\fP);
.ft
.fi
.SH DESCRIPTION
\f[CB]getcwd\fP
copies the absolute path name of the current directory info into
.I buf
of length
.IR len .
The return path may be longer than
\f[CB]PATH_MAX\fR.
If
.I "buff == 0"
then space is allocated via
.IR malloc (3)
and
.I len
extra characters are reserved after the generated path name.
A pointer to the path name is returned,
\f[CB]NULL\fP
on error.
.SH "SEE ALSO"
.IR path (3)
