.TH IBLOCKS 3
.SH NAME
iblocks \- compute the number of blocks used by a file
.SH SYNOPSIS
.nf
.ft CW
#include <ls.h>

long     _iblocks(struct stat* \fIst\fP);
.ft
.fi
.SH DESCRIPTION
\f(CW_iblocks\fP
returns the number of blocks used by the file whose
.IR stat (2)
information is pointed to by
.IR st .
The count includes both data and indirect blocks.
.PP
This routine is used by
.B <ls.h>
on system without the
\f(CWstruct stat \fP st_blocks
field.
.SH "SEE ALSO"
ls(1), stat(2)
