.TH IBLOCKS 3
.SH NAME
iblocks \- compute the number of blocks used by a file
.SH SYNOPSIS
.nf
.ft CR
#include <ls.h>

long     iblocks(struct stat* \fIst\fP);
.ft
.fi
.SH DESCRIPTION
\f[CB]iblocks\fP
returns the number of blocks used by the file whose
.IR stat (2)
information is pointed to by
.IR st .
The count includes both data and indirect blocks.
.PP
This routine even works
on systems without the
\f[CB]struct stat\fP
.I st_blocks
field.
.SH "SEE ALSO"
.IR ls (1),
.IR stat (2)
