.TH PATH 3
.SH NAME
path \- file path routines
.SH SYNOPSIS
.nf
.ft CR
#include <ast.h>

char*     pathaccess(char* \fIpath\fP, const char* \fIdirs\fP, const char* \fIa\fP, const char* \fIb\fP, int \fImode\fP);
char*     pathbin(void);
char*     pathcanon(char* \fIpath\fP, int \fIflags\fP);
char*     pathcat(char* \fIpath\fP, const char* \fIdirs\fP, int \fIsep\fP, const char* \fIa\fP, const char* \fIb\fP);
int       pathcd(const char* \fIpath\fP, const char* \fIhome\fP);
int       pathexists(char* \fIpath\fP, int \fImode\fP);
ssize_t   pathgetlink(const char* \fIname\fP, char* \fIbuf\fP, size_t \fIsiz\fP);
int       pathicase(const char* \fIpath\fP);
size_t    pathnative(const char* \fIpath\fP, char* \fIbuf\fP, size_t \fIsiz\fP);
char*     pathpath(char* \fIpath\fP, const char* \fIp\fP, const char* \fIa\fP, int \fImode\fP);
size_t    pathposix(const char* \fIpath\fP, char* \fIbuf\fP, size_t \fIsiz\fP);
char*     pathrepl(char* \fIpath\fP, const char* \fImatch\fP, const char* \fIreplace\fP);
int       pathsetlink(const char* \fItext\fP, char* \fIname\fP);
int       pathstat(const char* \fIpath\fP, struct stat* \fIst\fP);
char*     pathtemp(char* \fIpath\fP, size_t \fIlen\fP, const char* \fIdir\fP, const char* \fIpfx\fP, int* \fIfdp\fP);
.ft
.fi
.SH DESCRIPTION
These routines operate on file path names.
Path buffers are assumed to be of size
\f[CB]PATH_MAX\fP.
\f[CB]<ast.h>\fP
always defines
\f[CB]PATH_MAX\fP,
even if it's indeterminate on the local system.
Yes, this was probably a bad choice, but it was made in the 1980s.
We will probably move to a <stk.h> based implementation.
.PP
\f[CB]pathaccess\fP
constructs a path in
.I path
to the file
.I a/b
with access
.I mode
using the
\f[CB]:\fP
separated directories in
.IR dirs .
Both
.I a
and
.I b
may be
\f[CB]NULL\fP.
If
.I a
is
\f[CB]..\fP
then relative directories in
.I dirs
are ignored.
.I mode
is the inclusive-or of:
.TP
\f[CB]PATH_READ\fP
Read permission on file.
.TP
\f[CB]PATH_WRITE\fP
Write permission on file.
.TP
\f[CB]PATH_EXECUTE\fP
Execute permission on file.
.TP
\f[CB]PATH_REGULAR\fP
A regular file.
.TP
\f[CB]PATH_ABSOLUTE\fP
Generated path name is rooted at
\f[CB]/\fP.
.IP
.I path
is returned,
\f[CB]NULL\fP
on error.
.PP
\f[CB]pathbin\fP
returns a pointer to the
\f[CB]:\fP
separated list of directories to search for executable commands.
The
\f[CB]PATH\fP
environment variable is first consulted.
If not defined then
\f[CB]confstr(_CS_PATH,...)\fP
is used.
A valid string is always returned.
.PP
\f[CB]pathcanon\fP
canonicalizes the path
.I path
in place.
A pointer to the trailing 0 in the canonicalized path is returned.
A canonical path has:
redundant
\f[CB].\fP
and
\f[CB]/\fP
removed;
\f[CB]..\fP
moved to the front;
\f[CB]/..\fP
preserved for super root hacks.
.I flags
is the inclusive-or of:
.TP
\f[CB]PATH_DOTDOT\fP
Each
\f[CB]..\fP
is checked for access.
.TP
\f[CB]PATH_EXISTS\fP
Path must exist at each component.
.TP
\f[CB]PATH_PHYSICAL\fP
Symbolic links are resolved at each component.
.PP
\f[CB]NULL\fP
is returned on error.
If an error occurs and either of
\f[CB]PATH_DOTDOT\fP
or
\f[CB]PATH_EXISTS\fP
is set then
.I path
will contain the components following the failure point.
.PP
\f[CB]pathcat\fP
concatenates the first
.I sep
separated path component in
.I dirs
with the path components
.I a
and
.I b
into
.IR path .
The path is constructed in
.I path
by separating each path component with
.IR / .
Both
.I a
and
.I b
may be
\f[CB]NULL\fP.
A pointer to the next
.I sep
separated component in
.I dirs
is returned,
\f[CB]NULL\fP
when there are no more components.
\f[CB]pathcat\fP
is used by
\f[CB]pathaccess\fP.
.PP
\f[CB]pathcd\fP
sets the current working directory to
.I path
via
.IR chdir (2).
If
.I path
is longer than
\f[CB]PATH_MAX\fP
then it is split up into a sequence of relative paths and
.I chdir
is called on each of these.
If an intermediate
.I chdir
fails and
.I home
is not
\f[CB]NULL\fP
then the current directory is restored to
.IR home .
0 is returned on success, \-1 on error.
For any given system, if you got to a directory, then
\f[CB]pathcd\fP
can get you back, modulo permission and link changes.
.PP
\f[CB]pathexists\fP
returns 1 if
.I path
exists with the access
.IR mode ,
0 otherwise.
.I mode
is the inclusive-or of the
\f[CB]PATH_READ\fP,
\f[CB]PATH_WRITE\fP,
\f[CB]PATH_EXECUTE\fP
and
\f[CB]PATH_REGULAR\fP
flags described for
\f[CB]pathaccess\fP.
A cache of recent results is maintained to minimize
.IR stat (2)
calls.
.PP
\f[CB]pathgetlink\fP
returns the 0-terminated symbolic link text for
.I name
in the buffer
.I buf
of size
.IR siz .
The link text length is returned on success, \-1 on error.
Weird
.IR universe (1)
interactions with dynamic symbolic links are handled
by converting non-standard dynamic link text to
\f[CB].../$(UNIVERSE)/...\fP
The
\f[CB]pathsetlink\fP
function
converts in the other direction.
.PP
\f[CB]pathicase\fP
uses an operating system-specific method, if available,
to determine if a file system uses case-insensitive file names.
The return value is
.B 1
if the file system associated with the
.I path
is case-insensitive (regardless of case preservation),
.B 0
if it is not, or
.B \-1
if an error occurred. On error,
\f[CB]errno\fP
is set by the system-specific function that was used.
If the operating system does not have a known method
to determine file system case insensitivity for the
.IR path ,
then
\f[CB]pathicase\fP
returns
.B \-1
with
\f[CB]errno\fP
set to
\f[CB]ENOSYS\fP.
.PP
\f[CB]pathnative\fP
converts the POSIX path
.I path
to the native file system representation in the buffer
.I buf
of size
.IR siz .
The length of the converted path is returned;
if the return value is >=
.I siz
then
.I buf
is indeterminate and the call should be retried with
.I siz
at least the returned value plus 1.
On systems with no distinct native representation the path is
copied verbatim.
.PP
\f[CB]pathpath\fP
constructs in
.I path
a path to
.I p
with
.IR access (2)
mode
.I mode
using the directories from
\f[CB]pathbin()\fP.
If
.I a
!=
\f[CB]NULL\fP
then
.IR a ,
.IR argv [0]
(if available via
.IR optget (3)),
and the
\f[CB]_\fP
environment variable (set by
.IR ksh (1))
are used for related root searching.
If
.I p
also contains a
\f[CB]/\fP
then
.I ../p
is searched for.
If
.I path
is 0 then space is allocated.
The path is returned,
\f[CB]NULL\fP
on error.
.PP
\f[CB]pathposix\fP
converts the native file system path
.I path
to the POSIX representation in the buffer
.I buf
of size
.IR siz .
The length of the converted path is returned;
if the return value is >=
.I siz
then
.I buf
is indeterminate and the call should be retried with
.I siz
at least the returned value plus 1.
On systems with no distinct native representation the path is
copied verbatim.
.PP
\f[CB]pathrepl\fP
does an in-place replacement of the first occurrence of
.I /match/
with
.I /replace/
in
.IR path .
.PP
\f[CB]pathsetlink\fP
creates a symbolic link
.I text
in the path
.IR name .
See
\f[CB]pathgetlink\fP
above for weird
.IR universe (1)
interactions hidden by this routine.
.PP
\f[CB]pathstat\fP
first tries
\f[CB]stat(\fP\fIpath\fP\f[CB],\fP \fIst\fP\f[CB])\fP
and if that fails it tries
\f[CB]lstat(\fP\fIpath\fP\f[CB],\fP \fIst\fP\f[CB])\fP.
The
.I stat
or
.I lstat
return value is returned.
.PP
\f[CB]pathtemp\fP
generates in
.I path
a temporary file path name of the form
.IR dir / \fIpfx <base>.<suf>\fP
where the length of
.IR pfx ,
if !=0, is limited to 5, the length of
.I <base>
is limited to 3, and
.I <suf>
(an internally generated suffix that avoids file conflicts)
is limited to 3.
The generated path name conforms to the classic UNIX 14 char and the DOS
\f[CB]8.3\fP
limitations.
If
.I len
is not 0 then it is the size of
.IR path ;
if
.I path
is 0 then space of size
.I len
(or
\f[CB]PATH_MAX\fP
if
.I len
is 0) is allocated.
Both
.I dir
and
.I pfx
may be
\f[CB]NULL\fP,
in which case the
\f[CB]TMPPATH\fP
and
\f[CB]TMPDIR\fP
environment variables and a compiled-in default directory are consulted.
If
.I fdp
is not 0 then the file is atomically created with
.B O_EXCL
and the open file descriptor is stored in
.IR *fdp .
The generated path name is returned, 0 on error.
.IR access (2)
is used to avoid file conflicts when
.I fdp
is 0, but the generated path name is then not created,
so you could lose in a race.
.SH "SEE ALSO"
.IR access (2),
.IR confstr (3),
.IR lstat (2),
.IR stat (2)
