.TH PROC 3
.SH NAME
proc \- process control routines (deprecated)
.SH SYNOPSIS
.nf
.ft CW
#include <proc.h>

Proc_t* procopen(const char* \fIcommand\fP, char** \fIargv\fP, char** \fIenvv\fP, int64_t* \fIopv\fP, int \fIflags\fP);
int procfree(Proc_t* \fIproc\fP);
int procclose(Proc_t* \fIproc\fP);
int procrun(const char* \fIcommand\fP, char** \fIargv\fP);
.ft
.fi
.SH DESCRIPTION
These routines provide a portable interface to process creation and execution.
They used to work on systems with only
.IR spawnve (2)
or
.IR spawnveg (3).
Now that libast has joined the 21st century and requires
.IR fork (2)
and
.IR execve (2),
this interface is deprecated and only kept for backward compatibility.
.PP
\f(CWprocopen\fP
runs
.I command
with arguments
.IR argv ,
environment modifications in
.IR envv ,
file descriptor, signal and process group operations in
.I opv
and flags in
.IR flags .
.PP
.I command
is searched for using the
\f(CWPATH\fP
environment variable from the calling environment.
If
.I command
is
\f(CW0\fP
then the shell returned by
.IR astconf (3)
is used.
If
.I envv
is not
\f(CW0\fP
then it is a
\f(CW0\fP
terminated vector of
\fIname\fP[=\fIvalue\fP]
strings that are added to the
.I command
environment using
.IR setenviron (3).
If
.I name
appears in the parent environment then its value is replaced with the new
.IR value .
If
.RI = value
is omitted then
.I name
is removed from the child environment.
The
\f(CW_\fP
environment variable is set to contain the pathname for
.I command
and will appear at the top of the child environment.
.PP
If
.I opv
is not
\f(CW0\fP
then it is a zero-terminated vector of operations to perform.
In the following
.I context
is a combination of
\f(CWPROC_FD_CHILD\fP
and
\f(CWPROC_FD_PARENT\fP
for the child and parent process context respectively.
Valid operations are:
.TP
\f3PROC_FD_CLOSE(\fIfd\fP, \fIcontext\fP)\fR
The file descriptor
.I fd
is closed in
.IR context .
.TP
\f3PROC_FD_DUP(\fIfrom\fP, \fIto\fP, \fIcontext\fP)\fR
The file descriptor
.I from
is
.IR dup (2)'d
into the file descriptor
.I to
in
.IR context .
.TP
\f3PROC_SIG_DFL(\fIsig\fP)\fR
The signal handler for
.I sig
is set to
\f(CWSIG_DFL\fP
in the child context.
.TP
\f3PROC_SIG_IGN(\fIsig\fP)\fR
The signal handler for
.I sig
is set to
\f(CWSIG_IGN\fP
in the child context.
.TP
\f3PROC_SYS_PGRP(\fIpgid\fP)\fR
The child process group is set to
.IR pgid .
.I pgid
may have the following values:
.TP
\f(CW<0\fP
The child process becomes a session leader.
.TP
\f(CW0\fP
The child process is in the parent process group.
.TP
\f(CW1\fP
The child process becomes a process group leader.
.TP
\f(CW>1\fP
The child process joins the process group
.IR pgid .
.TP
\f3PROC_SYS_UMASK(\fImask\fP)\fR
The child process group file creation mask is set to
.IR mask .
.PP
.I flags
is the inclusive-or of the following:
.TP
\f(CWPROC_ARGMOD\fP
.I "argv[-1]"
and
.I "argv[0]"
may be modified.
This is an optimization that avoids an environment vector
.I realloc(3)
when
.I command
is a shell script.
.TP
\f(CWPROC_BACKGROUND\fP
Standard shell
\f(CW&\fP
setup is done for the child process.
.TP
\f(CWPROC_CLEANUP\fP
Parent process redirection file descriptors are closed on error.
.TP
\f(CWPROC_DAEMON\fP
Standard daemon setup is done for the child process.
.TP
\f(CWPROC_ENVCLEAR\fP
The child environment is cleared before
.I envv
is added.
.TP
\f(CWPROC_GID\fP
The child effective group ID is set to the real group ID.
.TP
\f(CWPROC_IGNORE\fP
Parent pipe errors are ignored.
.TP
\f(CWPROC_OVERLAY\fP
The current process is overlaid by
.I command
if possible
(i.e., the
.IR fork (2)
call is omitted).
.TP
\f(CWPROC_PARANOID\fP
Paranoid:
.I command
is searched using the default standard
\f(CWPATH\fR;
the child environment variable
\f(CWPATH\fP
is set to the default standard;
the
\f(CWPROC_GID\fP
and
\f(CWPROC_UID\fP
modes are set;
only
\f(CW/bin/sh\fP
is used to execute
.I command
if it is a shell script.
.TP
\f(CWPROC_PRIVILEGED\fP
If the effective user ID is
\f(CW0\fP
then the child real user ID is set to
\f(CW0\fP
and the child real group ID is set to the effective group ID.
.TP
\f(CWPROC_READ\fP
.I proc.rfd
is connected to
.IR command 's
standard output.
.TP
\f(CWPROC_SESSION\fP
The child process becomes a session group leader.
(Equivalent to the
.I opv
entry
\f(CWPROC_SYS_PGRP(-1)\fR.)
.TP
\f(CWPROC_UID\fP
The child effective user ID is set to the real user ID.
.TP
\f(CWPROC_WRITE\fP
.I proc.wfd
is connected to
.IR commands 's
standard input.
.PP
The return value is a pointer to a structure with the following members:
.TP
\f(CWpid_t \fIpid\fP\fP
The child process ID.
.TP
\f(CWpid_t \fIpgrp\fP\fP
The child process group.
.TP
\f(CWint \fIrfd\fP\fP
A read file descriptor connected to
.IR command 's
standard output.
.TP
\f(CWint \fIwfd\fP\fP
A write file descriptor connected to
.IR command 's
standard input.
.PP
If an error occurs then
\f(CW0\fP
is returned.
.PP
\f(CWprocclose\fP
waits for the process
.I proc
to complete and then closes the command stream
.IR proc .
The command exit status is returned.
\f(CW-1\fP
is returned if the child portion of
\f(CWprocopen\fP
failed.
.PP
\f(CWprocfree\fP
frees the process stream without waiting for
.I command
to complete.
Presumably some other mechanism will be used to wait for
.IR proc.pid .
.PP
\f(CWprocrun\fP
combines
\f(CWprocopen\fP
and
\f(CWprocclose\fP
with the flags
\f(CWPROC_GID|PROC_UID\fP
and returns the command exit status.
.SH "SEE ALSO"
popen(3), sfpopen(3), spawnveg(3), system(3)
