.TH LIBAST 3
.SH NAME
setenviron \- set environment value
.SH SYNOPSIS
.nf
.ft CR
#include <ast.h>

char*     setenviron(const char* \fIkey\fP);
.ft
.fi
.SH DESCRIPTION
\f[CB]setenviron\fP
controls environment
.I name=value
pairs.
\f[CB]setenviron("\fIname=value\fP")\fP
adds
.I name
to the environment and returns a pointer to a
.IR strdup (3)
copy of
.IR name=value .
\f[CB]setenviron("\fIname\fP")\fP
removes
.I name
from the environment and returns the empty string.
\f[CB]setenviron(0)\fP
reserves a few slots in an internal array and is usually called by
a parent process that expects many children.
0 is returned on error.
\f[CB]setenviron\fP
preserves the
.IR ksh (1)
convention of
\f[CB]_\fP
as the first environment variable name.
.SH "SEE ALSO"
.IR env (1),
.IR execve (2),
.IR exec (3),
.IR environ (7)
