.TH LIBAST 3
.SH NAME
setenviron \- set environment value
.SH SYNOPSIS
.nf
.ft CW
#include <ast.h>

char*     setenviron(const char* \fIkey\fP);
.ft
.fi
.SH DESCRIPTION
\f(CWsetenviron\fP
controls environment
.I name=value
pairs.
\f(CWsetenviron("\fIname=value\fP")\fP
adds
.I name
to the environment and returns a pointer to a
.IR strdup (3)
copy of
.IR name=value .
\f(CWsetenviron("\fIname\fP")\fP
removes
.I name
from the environment and returns the empty string.
\f(CWsetenviron(0)\fP
reserves a few slots in an internal array and is usually called by
a parent process that expects many children.
0 is returned on error.
\f(CWsetenviron\fP
preserves the
.IR ksh (1)
convention of
\f(CW_\fP
as the first environment variable name.
.SH "SEE ALSO"
env(1), exec(2)
