.TH SPAWNVEG 3
.SH NAME
spawnveg \- process spawn with process group and session control
.SH SYNOPSIS
\f[CB]#include <ast.h>\fP
.sp
\f[CB]int spawnveg(const char* command, char** argv, char** envv, pid_t pgid, int tcfd);\fP
.SH DESCRIPTION
\f[CB]spawnveg\fP
combines
.IR fork (2),
.IR exec (2),
.IR setpgid (2)
and
.IR setsid (2)
into a single call.
If one of either
.IR posix_spawn (3)
or
.IR clone (2)
is available, those functions are preferred over
.IR fork .
.PP
\f[CB]command\fR,
\f[CB]argv\fP
and
\f[CB]envv\fP
are as in
.IR execve (2).
\f[CB]pgid\fP
controls the new process group and session:
.TP
\f[CB]-1\fP
The new process becomes a session leader.
.IR setsid (2)
is called in the child context.
.TP
\f[CB]0\fP
The new process is in the caller's process group.
.TP
\f[CB]1\fP
The new process becomes a process group leader.
.TP
\f[CB]>1\fP
The new process joins the process group
.IR pgid .
.PP
When
\f[CB]tcfd\fP
is
\f[CB]>=0\fR,
spawnveg will set the controlling terminal for the new process to
.IR tcfd ,
and will set the terminal signals
.IR SIGTSTP ,
.IR SIGTTIN ,
and
.I SIGTTOU
to their defaults in the child process before
.I execve
is called.
.SH CAVEATS
If
.I clone
and/or
.I POSIX_SPAWN_SETSID
aren't available, then
\f[CB]spawnveg\fP
will fall back to using
.I fork
in cases where either
.I setsid
or
.IR tcsetpgrp (3)
is required.
.SH "SEE ALSO"
.IR fork (2),
.IR posix_spawn (3),
.IR clone (2),
.IR exec (2),
.IR setpgid (2),
.IR setsid (2),
.IR sigaction (2),
.IR spawnve (2),
.IR tcsetpgrp (3)
