.TH STRCOPY 3
.SH NAME
strcopy \- copy strings
.SH SYNOPSIS
\f[CB]char* strcopy(char* a, char* b)\fP
.SH DESCRIPTION
.I strcopy
copies the null-terminated string
.I b
into
.IR a .
A pointer to the 0 character in
.I a
is returned.
.PP
Unlike C library functions like
.IR strcpy (3),
this function does
.I not
have undefined behaviour if the source and destination buffers overlap.
.SH "SEE ALSO"
.IR strcpy (3),
.IR stpcpy (3)
