.TH STRDUP 3
.SH NAME
strdup \- duplicate null-terminated string
.SH SYNOPSIS
\f[CB]char* strdup(const char* s)\fP
.SH DESCRIPTION
.I strdup
copies the null-terminated string
.I s
to a new location provided by
.IR malloc (3)
and returns a pointer to the new copy.
.B NULL
is returned if
.IR malloc (3)
failed.
.PP
If
.I s
is
.BR NULL ,
then this AST implementation of
.I strdup
returns
.BR NULL .
This differs from other implementations
in which the behavior is undefined in that case.
.SH "SEE ALSO"
.IR malloc (3),
.IR memdup (3)
