.TH STRELAPSED 3
.SH NAME
strelapsed \- parse elapsed time expression
.SH SYNOPSIS
\f(CWunsigned long strelapsed(const char* buf, char** next, int persec)\fP
.SH DESCRIPTION
.I strelapsed
returns a pointer to a string representation of the elapsed time for
\f(CW(count/persec)\fP
seconds.
The two largest time units are used, limiting the return value length
to at most 6 characters.
The units are:
.TP
.B s
seconds
.TP
.B m
minutes
.TP
.B h
hours
.TP
.B days
.TP
.B weeks
.TP
.B M
months
.TP
.B Y
years
.TP
.B S
scores
.SH "SEE ALSO"
strelapsed(3)
.SH CAVEATS
The return value points to a static area that is overwritten on each call.
