.TH STRESC 3
.SH NAME
stresc \- convert character constants in string
.SH SYNOPSIS
\f[CB]ptrdiff_t stresc(char* s)\fP
.SH DESCRIPTION
.I stresc
converts
\f[CB]\e\fP
character constant expressions in the null-terminated string
.I s
in place and returns the length of the converted
.IR s .
.SH "SEE ALSO"
.IR chresc (3),
.IR ctoi (3)
