.TH STRESC 3
.SH NAME
stresc \- convert character constants in string
.SH SYNOPSIS
\f(CWptrdiff_t stresc(char* s)\fP
.SH DESCRIPTION
.I stresc
converts
\f(CW\e\fP
character constant expressions in the null-terminated string
.I s
in place and returns the length of the converted
.IR s .
.SH "SEE ALSO"
chresc(3), ctoi(3)
