.TH STRGID 3
.SH NAME
strgid \- return group ID number for given group name
.SH SYNOPSIS
\f[CB]int strgid(const char* name)\fP
.SH DESCRIPTION
.I strgid
returns the group ID number for the given group name.
.I strgid
maintains an internal cache to avoid repeated password database scans
by the low level
.IR getgrgid (3).
On the first error for a given name,
.I strgid
returns -1.
Subsequent errors for the same name will result in
.I strgid
returning -2 instead.
.SH "SEE ALSO"
.IR getgrent (3)
