.TH STRMATCH 3
.SH NAME
strmatch \- match shell file patterns
.SH SYNOPSIS
\f(CWssize_t strmatch(const char* s, const char* p)\fP
.br
\f(CWchar* strsubmatch(const char* s, const char* p, regflags_t flags)\fP
.SH DESCRIPTION
.I strmatch
compares the string
.I s
with the shell pattern
.I p
and returns 1 for match and 0 otherwise.
.I strsubmatch
does a leading substring match of the shell pattern
.I p
with the string
.IR s .
If
.I flags
is 0 then the match is minimal, otherwise a maximal match is done.
A pointer to the first character after the matched substring is returned,
.I 0
if there is no match.
.PP
Except for
.I &
and
.IR ! ,
each shell pattern has an equivalent
.IR egrep (1)
construct.
.nf
.ft CW
	\fBsh pattern	egrep RE	description\fP
	*		.*		0 or more chars
	?		.		any single char
	[.]		[.]		char class
	[!.]		[^.]		negated char class
	*(.)		(.)*		0 or more of
	+(.)		(.)+		1 or more of
	?(.)		(.)?		0 or 1 of
	(.)		(.)		1 of
	@(.)		(.)		1 of
	a|b		a|b		a or b
	a&b				a and b
	!(.)				none of
.ft
.fi
\f(CW\e\fP
is used to escape *, ?, (, |, &, ), [, and \e
outside of [...].
.SH "SEE ALSO"
grep(1)
.SH BUGS
An unbalanced
\f(CW)\fP
terminates the top level pattern.
.br
Nested
\f(CW&\fP
and
\f(CW!\fP
constructs are non-intuitive and are computationally intensive.
