.TH STROPT 3
.SH NAME
stropt \- table driven option expression evaluator
.SH SYNOPSIS
\f(CW#include <namval.h>\fP
.br
\f(CWint stropt(const char* s, struct namval* tab, int siz,\fP
.br
\f(CW           int (*fun)(void* a, struct namval* p, int n, char* v),\fP
.br
\f(CW           void* a)\fP
.SH DESCRIPTION
.I stropt
parses option expressions in the null-terminated string
.I s
using the option names in
.IR tab .
.I tab
is an array of
.B "struct namval"
name value pairs:
.nf
.ft CW
char*	name;
int	value;
.ft
.fi
The last entry must be followed by a sentinel with
.B name
set to 0.
.PP
An option expression contains 0 or more of [\fBno\fP]\fIname\fP[=\fIvalue\fP]
separate by
.B space
or
.BR tab ,
where
.I name
must be one of the option names in
.IR tab ,
.I value
is an optional value, and
.B no
is for Boolean options.
Each option is passed to
.I fun
for processing.
.I a
is the
\f(CWvoid*\fP
pointer that is passed from the
.I stropt
call but is otherwise not interpreted.
.I p
points to the option name value pair from
.IR tab .
.I n
is 0 if
.B no
preceded the option
.I name
and
.I v
points to the beginning of the option
.I value
in
.IR s .
and
If
.I name
is not found in
.I tab
then
.I fun
is called with
.I p
pointing to an internal
.I namval
entry with
.I p\->name
pointing to the unknown option and
.I p\->value
set to the
.I value
of the sentinel entry in
.IR tab .
.PP
If
.I fun
returns non-zero then this value is returned and no further
options are processed.
Otherwise
.I stropt
returns 0 after processing all options.
