.TH STRSORT 3
.SH NAME
strsort \- array heap sort
.SH SYNOPSIS
.nf
.ft CR
#include <ast.h>

void    strsort(char** \fIarray\fP, int \fIelements\fP, int (*\fIcompare\fP)(const char* \fIa\fP, const char* \fIb\fP));
.ft
.fi
.SH DESCRIPTION
\f[CB]strsort\fP
does a heap sort on the array of pointers
.I array
with
.I elements
elements using the comparison function
.IR compare .
.I compare
returns
\f[CB]\-1\fP
if
.I a
is lexicographically less than
.IR b ,
\f[CB]0\fP
if
.I a
is equal to
.IR b ,
and
\f[CB]1\fP
if
.I a
is lexicographically greater than
.IR b .
