.TH STRUID 3
.SH NAME
struid \- return user ID number for given user name
.SH SYNOPSIS
.nf
.ft CR
int struid(const char* \fIname\fP)
.ft
.fi
.SH DESCRIPTION
.I struid
returns the user ID number for the given user name.
.I struid
maintains an internal cache to avoid repeated password database scans
by the low level
.IR getpwuid (3).
On the first error for a given name,
.I struid
returns -1.
Subsequent errors for the same name will result in
.I struid
returning -2 instead.
.SH "SEE ALSO"
.IR getpwent (3)
