.TH TMX 3
.SH NAME
tmx \- high resolution time conversion support
.SH SYNOPSIS
\f[CB]#include <tmx.h>\fP
.SH DESCRIPTION
The
.I tmx
library supports conversion between
string date specifications and
nanosecond resolution
\f[CB]Time_t\fP
clock values.
\f[CB]Time_t\fP
is the number of nanoseconds since the epoch,
.BR "Jan 1 00:00:00 UTC 1970" ,
with leap seconds omitted; it is a 64-bit integral type if the
implementation supports one, otherwise it is an emulated type.
The
\f[CB]tmxsec(\fP\fIt\fP\f[CB])\fP
and
\f[CB]tmxnsec(\fP\fIt\fP\f[CB])\fP
macros extract the seconds and nanoseconds portions of
.IR t ,
and
\f[CB]tmxsns(\fP\fIs\fP, \fIn\fP\f[CB])\fP
composes a
\f[CB]Time_t\fP
from a seconds value
.I s
and a nanoseconds value
.IR n .
\f[CB]TMX_NOW\fP
is the current time,
\f[CB]TMX_NOTIME\fP
is a distinguished invalid time, and
\f[CB]TMX_MAXTIME\fP
is the maximum representable time.
.PP
The routines are:
.TP
\f[CB]Time_t tmxdate(const char* \fIdate\fP, char** \fIend\fP, Time_t \fInow\fP)\fP
Parses the date specification
.I date
and returns the equivalent
\f[CB]Time_t\fP
value.
If
.I end
is not
\f[CB]NULL\fP
then it is set to the position of the first unrecognized character in
.IR date .
.I now
provides default values for omitted components in
.IR date .
.TP
\f[CB]Time_t tmxduration(const char* \fIspan\fP, char** \fIend\fP)\fP
Parses the duration specification
.I span
(an ISO 8601
.B P
duration or a number followed by a unit)
and returns the equivalent number of nanoseconds.
If
.I end
is not
\f[CB]NULL\fP
then it is set to the position of the first unrecognized character in
.IR span .
.TP
\f[CB]char* tmxfmt(char *\fIrestrict buf\fP, size_t \fIlen\fP, const char *\fIrestrict format\fP, Time_t \fIt\fP)\fP
Formats the time
.I t
into the buffer
.I buf
with size
.I len
bytes according to the format specification
.IR format .
A pointer to the end of
.I buf
(i.e., the terminating
\f[CB]'\e0'\fP)
is returned.
The format directives are the same as those of
\f[CB]tmfmt\fP
described in
.BR tm (3),
with nanosecond resolution for the
.BR %N ,
.B %s
and
.B %S
fields.
\f[CB]tmfmt()\fP
is a seconds-resolution wrapper around
\f[CB]tmxfmt()\fP.
.TP
\f[CB]Time_t tmxleap(Time_t \fIt\fP)\fP
Returns
.I t
with leap seconds adjusted for external routines that do not handle
leap seconds.
Adjustments are only done if the
\f[CB]TM_ADJUST\fP
flag is set in
\f[CB]tm_info.flags\fP
(see
.BR tm (3)).
.TP
\f[CB]Tm_t* tmxmake(Time_t \fIt\fP)\fP
Returns a pointer to the
\f[CB]Tm_t\fP
struct (see
.BR tm (3))
corresponding to the time
.IR t .
.TP
\f[CB]Time_t tmxscan(const char* \fIdate\fP, char** \fIend\fP, const char* \fIformat\fP, char** \fIfmt\fP, Time_t \fInow\fP, long \fIflags\fP)\fP
Scans the date specification
.I date
using the
.BR strptime (3)-style
.I format
(or one of the formats in the
.I fmt
list) and returns the equivalent
\f[CB]Time_t\fP
value, with
.I now
providing defaults for omitted components.
.TP
\f[CB]int tmxsleep(Time_t \fIt\fP)\fP
Suspends execution for the time span
.IR t .
0 is returned on success, \-1 on error or interruption.
.TP
\f[CB]Time_t tmxtime(Tm_t* \fItp\fP, int \fIwest\fP)\fP
Returns the
\f[CB]Time_t\fP
value corresponding to the
\f[CB]Tm_t\fP
struct
.IR tp .
If
.I west
is
\f[CB]TM_LOCALZONE\fP
then
.I tp
is relative to the local time zone,
otherwise
.I west
is the number of minutes west of
.B UTC .
.TP
\f[CB]Tm_t* tmxtm(Tm_t* \fItp\fP, Time_t \fIt\fP, Tm_zone_t* \fIzone\fP, const char \fInewzone\fP)\fP
Sets
.I tp
to the
\f[CB]Tm_t\fP
breakdown of
.I t
relative to the time zone
.IR zone ,
or the current reference time zone if
.I zone
is 0.
.I tp
is returned.
.TP
\f[CB]Time_t tmxgettime(void)\fP
Returns the current time.
.TP
\f[CB]int tmxsettime(Time_t \fIt\fP)\fP
Sets the system time to
.IR t .
The caller must have sufficient privilege.
0 is returned on success, \-1 on error.
.TP
\f[CB]int tmxtouch(const char* \fIpath\fP, Time_t \fIat\fP, Time_t \fImt\fP, Time_t \fIct\fP, int \fIflags\fP)\fP
Sets the file
.I path
access time from
.IR at ,
modify time from
.IR mt ,
and change time from
.IR ct .
Unless
\f[CB]PATH_TOUCH_VERBATIM\fP
is set in
.IR flags ,
a time value of 0 uses the current time and a time value of
\f[CB]TMX_NOTIME\fP
retains the previous file value.
0 is returned on success, \-1 on error.
.SH "SEE ALSO"
.IR tm (3),
.IR tv (3)
