.TH TOUCH 3
.SH NAME
touch \- set file access and modify times
.SH SYNOPSIS
\f(CW#include <ast.h>\fP
.sp
\f(CWint touch(const char* path, time_t atime, time_t mtime, int force);\fP
.SH DESCRIPTION
\f(CWtouch\fP
sets the access and modify times of the file named by
\f(CWpath\fR.
If
\f(CWforce != 0\fP
then the file is created if it doesn't exist;
otherwise the file is not created and
\f(CW\-1\fP
is returned.
If
\f(CWforce < 0\fP
then
\f(CWatime\fP
and
\f(CWmtime\fP
are taken verbatim; otherwise
\f(CW(time_t)(-1)\fP
retains the current value for the file and
\f(CW(time_t)(0)\fP
uses the current time.
.SH CAVEATS
By default the change time is always changed to the current time.
