.TH TOUCH 3
.SH NAME
touch \- set file access and modify times
.SH SYNOPSIS
\f[CB]#include <ast.h>\fP
.sp
\f[CB]int touch(const char* path, time_t atime, time_t mtime, int force);\fP
.SH DESCRIPTION
\f[CB]touch\fP
sets the access and modify times of the file named by
\f[CB]path\fR.
If
\f[CB]force != 0\fP
then the file is created if it doesn't exist;
otherwise the file is not created and
\f[CB]\-1\fP
is returned.
If
\f[CB]force < 0\fP
then
\f[CB]atime\fP
and
\f[CB]mtime\fP
are taken verbatim; otherwise
\f[CB](time_t)(-1)\fP
retains the current value for the file and
\f[CB](time_t)(0)\fP
uses the current time.
.SH CAVEATS
By default the change time is always changed to the current time.
