.TH TV 3
.SH NAME
tv \- high resolution time support
.SH SYNOPSIS
\f[CB]#include <tv.h>\fP
.SH DESCRIPTION
The
.I tv
library supports high resolution
.B Tv_t
time specifications.
.B Tv_t
contains these elements:
.TP
\f[CB]time_t tv_sec\fP
Seconds since the epoch.
.TP
\f[CB]uint32_t tv_nsec\fP
Nanosecond resolution.
.PP
In practice resolution is much coarser than 1 nanosecond.
Systems that only support 1 second resolution always set
\f[CB]tv_nsec\fP
to 0.
.SS "int tvgettime(Tv_t* tv)"
Sets
\f[CB]tv\fP
to the current time.
\f[CB]0\fP
is returned on success,
\f[CB]-1\fP
on error.
.SS "int tvsettime(const Tv_t* tv)"
Sets the system time to
.IR tv .
The caller must have sufficient privilege.
\f[CB]0\fP
is returned on success,
\f[CB]-1\fP
on error.
.SS "int tvcmp(const Tv_t* av, const Tv_t* bv)"
Compares the times
.I av
and
.I bv
and returns
\f[CB]-1\fP
if
.I av
is less than
.IR bv ,
\f[CB]0\fP
if
.I av
is equal to
.IR bv ,
and
\f[CB]1\fP
if
.I av
is greater than
.IR bv .
.SS "time_t tvgetatime(Tv_t* tv, const struct stat* st)"
.SS "time_t tvgetmtime(Tv_t* tv, const struct stat* st)"
.SS "time_t tvgetctime(Tv_t* tv, const struct stat* st)"
These macros set
.I tv
to the
.I st
access, modify, or change time, respectively.
The seconds portion of
.I tv
is returned.
.SS "time_t tvsetatime(Tv_t* tv, struct stat* st)"
.SS "time_t tvsetmtime(Tv_t* tv, struct stat* st)"
.SS "time_t tvsetctime(Tv_t* tv, struct stat* st)"
These macros set the
.I st
access, modify, or change time, respectively, to
.IR tv .
The seconds portion of
.I tv
is returned.
.SS "int tvtouch(const char* path, const Tv_t* av, const Tv_t* mv, const Tv_t* cv, int flags)"
Sets the file
.I path
access time from
.IR av ,
modify time from
.IR mv ,
and change time from
.IR cv .
Each of
.IR av ,
.IR mv ,
and
.I cv
may be 0 to set the corresponding file time to the current time, or
\f[CB]TV_TOUCH_RETAIN\fP
to retain the previous file value if
.I path
exists (the current time is used otherwise);
any other value is the exact time to set.
.I flags
is the inclusive-or of:
.TP
\f[CB]TV_TOUCH_CREATE\fP
Create
.I path
if it does not exist.
.TP
\f[CB]TV_TOUCH_PHYSICAL\fP
Do not follow symbolic links.
.PP
.RS
.I cv
is ignored on most implementations.
\f[CB]0\fP
is returned on success,
\f[CB]-1\fP
on error.
.RE
.SS "int tvsleep(const Tv_t* tv, Tv_t* rv)"
Pauses execution for
.I tv
time.
\f[CB]0\fP
is returned if the full
.I tv
amount has expired.
Otherwise
\f[CB]-1\fP
is returned and
.IR rv ,
if not 0, is set to the sleep time remaining.
.SH "RETURN VALUE"
Except for
\f[CB]tvcmp()\fP,
an error return of
\f[CB]-1\fP
also sets
\f[CB]errno\fP
to the corresponding error code.
.SH "SEE ALSO"
.IR tm (3),
.IR tmx (3)
