########################################################################
#                                                                      #
#              This file is part of the ksh 93u+m package              #
#             Copyright (c) 2026 Contributors to ksh 93u+m             #
#                      and is licensed under the                       #
#                 Eclipse Public License, Version 2.0                  #
#                                                                      #
#                A copy of the License is available at                 #
#      https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html      #
#         (with md5 checksum 84283fa8859daf213bdda5a9f8d1be1d)         #
#                                                                      #
#              Siteshwar Vashisht <svashisht@redhat.com>               #
#                  Martijn Dekker <martijn@inlv.org>                   #
#                                                                      #
########################################################################

# Tests for the shell history file, including locking and concurrent access.
. "${SHTESTS_COMMON:-${0%/*}/_common}"

((!SHOPT_SCRIPTONLY)) || { warning "interactive shell was compiled out -- tests skipped"; exit 0; }

# use maximum possible history size by default for these tests
HISTSIZE=16384

# ======
# Between 2025-05-30 and 2026-09-02, 'print -s' failed to write to the history file.
# https://github.com/ksh93/ksh/issues/1019
exp=hello$$
got=$(print -s "hello$$"; fc -l -0 2>&1)
[[ $got == *[$'\t ']"$exp" ]] || err_exit "print -s fails to write to history file" \
	"(expected match of *[\t ]$(printf %q "$exp"), got $(printf %q "$got"))"

# ======
# The tests until the next '# ======' were generated by Claude Opus 4.6 directed by Siteshwar
# Vashisht on 2026-09-02, then corrected and largely rewritten by Martijn Dekker.
# See https://github.com/ksh93/ksh/issues/997 and https://github.com/ksh93/ksh/pull/1020

# Basic sanity: a single interactive session writes and retains history
histfile=$tmp/hist_basic
got=$(
	HISTFILE=$histfile
	print -s "echo alpha"
	print -s "echo bravo"
	print -s "echo charlie"
	fc -l -N 3 2>&1
)
[[ $got == *alpha* && $got == *bravo* && $got == *charlie* ]] \
	|| err_exit "single session: print -s entries not retained in history (got $(printf %q "$got"))"
[[ -f $histfile ]] || err_exit "HISTFILE not created"

# History file survives re-open
histfile=$tmp/hist_reopen
HISTFILE=$histfile
print -s "first_session_cmd"
HISTFILE=/dev/null
got=$(HISTFILE=$histfile; fc -l -N 5 2>&1)
[[ $got == *first_session_cmd* ]] \
	|| err_exit "history entry from prior session not visible after reopen (got $(printf %q "$got"))"

# Concurrent writes to the same HISTFILE
# note: n_sessions * n_lines should be < 16384
histfile=$tmp/hist_concurrent
typeset -i n_sessions=64 n_lines=255 present total
typeset -Z3 s i
for ((s=0; s<n_sessions; s++))
do	(
		HISTFILE=$histfile
		typeset -Z3 i
		for ((i=0; i<$n_lines; i++))
		do	print -s "session_${s}_cmd_${i}"
		done
	) &
done
wait
# read back
((total = n_sessions * n_lines))
got=$(
	HISTFILE=$histfile
	fc -l -N "$((n_sessions * n_lines + 50))" 2>&1 | sed $'s/^[0-9]*[ \t]*//' | LC_ALL=C sort
)
present=$(print "$got" | wc -l)
if	((present == total))
then	exp=
	for ((s=0; s<n_sessions; s++))
	do	for ((i=0; i<n_lines; i++))
		do	exp+=${exp:+$'\n'}session_${s}_cmd_${i}
		done
	done
	test "$got" = "$exp" || err_exit "concurrent history writes: got $total entries as expected, but entries differ." \
		$'Diff follows:\n'"$(diff -u <(print -r -- "$exp") <(print -r -- "$got") | sed $'s/^/\t| /; 25s/.*/\t| [...]/; 26,$d')"
else	err_exit "concurrent history writes: expected $total entries, got $present." \
		$'Diff follows:\n'"$(diff -u <(print -r -- "$exp") <(print -r -- "$got") | sed $'s/^/\t| /; 25s/.*/\t| [...]/; 26,$d')"
fi
unset n_sessions n_lines s present total

# History trimming
typeset -i size1 size2
mkdir hist_trim
histfile=$tmp/hist_trim/sh_history
(
	HISTFILE=$histfile
	typeset -i i
	for ((i=0; i<1000; i++))
	do	print -s "trimtest_cmd_${i}"
	done
) >/dev/null 2>&1				# older ksh misdirects 'print -s' to stdout or stderr here
size1=$(wc -c <$histfile)
touch -d '2020-07-12T01:43:13' "$histfile"	# make the history file 'old' to force a physical trim of the file
chmod a-w hist_trim				# verify that trimming works with a non-writable parent directory
# only the last 50 entries should survive; 'print -s' triggers the trim
(
	HISTSIZE=50
	HISTFILE=$histfile
	print -s extra1001
) >/dev/null 2>&1				# older ksh misdirects 'print -s' to stdout or stderr here
chmod +w hist_trim				# avoid interfering with cleanup (rm -rf)
size2=$(wc -c <$histfile)
((size2 < size1)) || err_exit "history file did not reduce in size ($size2 >= $size1)"
grep -q trimtest_cmd_999 "$histfile" || err_exit "most recent entry lost after trim"
grep -q trimtest_cmd_0 "$histfile" && err_exit "oldest entry not trimmed"
grep -q trimtest_cmd_949 "$histfile" && err_exit "last old entry not trimmed"
grep -q trimtest_cmd_950 "$histfile" || err_exit "first kept entry trimmed"
grep -q extra1001 "$histfile" || err_exit "extra entry not added"
unset size1 size2

# Rapidly alternating sessions: open, write one entry, close; repeat
# with the same HISTFILE. Tests lock acquire/release cycling.
typeset -i s total=1000 present missing
histfile=$tmp/hist_cycle
exp=
for ((s=0; s<total; s++))
do	HISTFILE=$histfile
	print -s "cycle_cmd_$s"
	HISTFILE=/dev/null
done
HISTFILE=$histfile
got=$(fc -l -N "$((total + 15))" 2>&1 | sed $'s/^[0-9]*[ \t]*//')
present=$(print "$got" | wc -l)
if	((present == total))
then	exp=
	for ((s=0; s<total; s++))
	do	exp+=${exp:+$'\n'}cycle_cmd_$s
	done
	test "$got" = "$exp" || err_exit "sequential session cycling: got $total entries as expected, but entries differ." \
		$'Diff follows:\n'"$(diff -u <(print -r -- "$exp") <(print -r -- "$got") | sed $'s/^/\t| /; 25s/.*/\t| [...]/; 26,$d')"
else	err_exit "sequential session cycling: expected $total entries, got $present." \
		$'Diff follows:\n'"$(diff -u <(print -r -- "$exp") <(print -r -- "$got") | sed $'s/^/\t| /; 25s/.*/\t| [...]/; 26,$d')"
fi
unset s total present missing
HISTFILE=/dev/null

# Stress test 1: many concurrent sessions each writing one line, history file reinitialised for each line
histfile=$tmp/hist_stress_1
typeset -i total=2000 present s
for ((s=0; s<total; s++))
do	(HISTFILE=$histfile; print -s "stress_cmd_$s") &
done
wait
got=$(HISTFILE=$histfile; fc -l -N 1 2>&1)
[[ e=$? -eq 0 && -n $got ]] || err_exit "ksh produced no history output after $total concurrent sessions" \
	"(got status $e, $(printf %q "$got")"
# verify history file's initial magic byte (HIST_UNDO == 8#201)
(LC_CTYPE=C; [[ $(<$histfile) == $'\201'* ]]) || err_exit "history file magic byte corrupted after stress test 1"
# read back
got=$(HISTFILE=$histfile; fc -l -N "$((total + 50))" 2>&1 | sed $'s/^[0-9]*[ \t]*//' | LC_ALL=C sort -n -t_ -k3)
present=$(print "$got" | wc -l)
if	((present == total))
then	exp=
	for ((s=0; s<total; s++))
	do	exp+=${exp:+$'\n'}stress_cmd_$s
	done
	test "$got" = "$exp" || err_exit "concurrent one-line stress test 1: got $total entries as expected, but entries differ." \
		$'Diff follows:\n'"$(diff -u <(print -r -- "$exp") <(print -r -- "$got") | sed $'s/^/\t| /; 25s/.*/\t| [...]/; 26,$d')"
else
	err_exit "concurrent one-line stress test 1: expected $total entries, got $present." \
		$'Diff follows:\n'"$(diff -u <(print -r -- "$exp") <(print -r -- "$got") | sed $'s/^/\t| /; 25s/.*/\t| [...]/; 26,$d')"
fi
unset total present s histfile

# Stress test 2: many concurrent sessions each writing one line, history file initialised once
HISTFILE=$tmp/hist_stress_2
typeset -i total=2000 present s
for ((s=0; s<total; s++))
do      print -s "stress_cmd_$s" &
done
wait
got=$(fc -l -N 1 2>&1)
[[ e=$? -eq 0 && -n $got ]] || err_exit "ksh produced no history output after $total concurrent sessions" \
	"(got status $e, $(printf %q "$got")"
# verify history file's initial magic byte (HIST_UNDO == 8#201)
(LC_CTYPE=C; [[ $(<$HISTFILE) == $'\201'* ]]) || err_exit "history file magic byte corrupted after stress test 2"
# read back
got=$(fc -l -N "$((total + 50))" 2>&1 | sed $'s/^[0-9]*[ \t]*//' | LC_ALL=C sort -n -t_ -k3)
present=$(print "$got" | wc -l)
if	((present == total))
then	exp=
	for ((s=0; s<total; s++))
	do	exp+=${exp:+$'\n'}stress_cmd_$s
	done
	test "$got" = "$exp" || err_exit "concurrent one-line stress test 2: got $total entries as expected, but entries differ." \
		$'Diff follows:\n'"$(diff -u <(print -r -- "$exp") <(print -r -- "$got") | sed $'s/^/\t| /; 25s/.*/\t| [...]/; 26,$d')"
else
	err_exit "concurrent one-line stress test 2: expected $total entries, got $present." \
		$'Diff follows:\n'"$(diff -u <(print -r -- "$exp") <(print -r -- "$got") | sed $'s/^/\t| /; 25s/.*/\t| [...]/; 26,$d')"
fi
unset total present s
HISTFILE=/dev/null

# ======
exit $((Errors<125?Errors:125))
