name: CI

on: [push]

jobs:

  Linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Build
      run: bin/package make
    - name: Regression tests
      run: |
        export TZ=GMT
        ulimit -n 1024
        script -q -e -c "bin/shtests"
